############################################################
# 04) A–C Coherence (NPMI & log2(Lift)) — ORIGINAL
# ----------------------------------------------------------
# Reproduces Figure 3 of the RA-ILD manuscript.
#
# Inputs:
#   output/cooc_npmi_lift_*.csv   (generated by 01)
#
# Outputs:
#   fig_pub/ac_npmi_lift_heatmap_{STAMP}.pdf
#   fig_pub/ac_npmi_lift_scatter_{STAMP}.pdf
#
# This script is the cleaned integration of:
#   - ac_npmi_lift_heatmap code (txt)
#   - coherence code inside the “Figure調整用追加コード.rtf” (final version)
#
# Path generalized:
ROOT <- "/path/to/RA-ILD_textanalysis"
############################################################

suppressPackageStartupMessages({
  library(dplyr); library(readr); library(stringr); library(tidyr)
  library(ggplot2); library(forcats); library(glue)
})

DIR_OUT <- file.path(ROOT, "output")
DIR_FIG <- file.path(ROOT, "fig_pub")
dir.create(DIR_FIG, recursive = TRUE, showWarnings = FALSE)

STAMP <- format(Sys.time(), "%Y%m%d_%H%M")
jpfont <- "sans"
cairo_pdf_device <- grDevices::cairo_pdf

############################################################
# 1) Load latest cooc_npmi_lift CSV
############################################################

pick_latest <- function(pattern, dir = DIR_OUT){
  xs <- Sys.glob(file.path(dir, pattern))
  if (!length(xs)) stop("cooc_npmi_lift_*.csv not found in: ", dir)
  xs[which.max(file.info(xs)$mtime)]
}

f_npmi <- pick_latest("cooc_npmi_lift_*.csv", DIR_OUT)
D0 <- read_csv(f_npmi, show_col_types = FALSE)

need_cols <- c("A","C","pA","pC","pAC","lift","npmi")
mis <- setdiff(need_cols, names(D0))
if (length(mis)) stop("Missing columns in CSV: ", paste(mis, collapse=", "))

############################################################
# 2) Preprocessing (RTF final logic)
############################################################

MIN_pAC   <- 0
TOP_PER_C <- 50

D <- D0 %>%
  mutate(
    log2_lift = log2(ifelse(lift > 0, lift, NA_real_)),
    A = as.character(A),
    C = as.character(C)
  ) %>%
  filter(!is.na(npmi), !is.na(log2_lift), pAC >= MIN_pAC)

# Select top-per-C by npmi (RTF準拠)
D <- D %>%
  group_by(C) %>%
  arrange(desc(npmi), desc(log2_lift), .by_group = TRUE) %>%
  mutate(rank_c = row_number()) %>%
  ungroup() %>%
  filter(rank_c <= TOP_PER_C)

# A/C ordering
ord_A <- D %>% group_by(A) %>%
  summarise(mr = mean(rank_c), .groups="drop") %>%
  arrange(mr) %>% pull(A)

ord_C <- D %>% count(C) %>% arrange(desc(n)) %>% pull(C)

D <- D %>%
  mutate(
    A = factor(A, levels = ord_A),
    C = factor(C, levels = ord_C)
  )

############################################################
# 3) Heatmap (NPMI & log2(Lift)) — Figure 3A
############################################################

clip <- function(x, lo, hi) pmin(pmax(x, lo), hi)

D_heat1 <- D %>%
  mutate(
    npmi_clip = clip(npmi, -0.2, 1.0),
    metric    = factor("NPMI", levels=c("NPMI","log2(Lift)")),
    value     = npmi_clip
  )

D_heat2 <- D %>%
  mutate(
    l2l_clip  = clip(log2_lift, -2, 2),
    metric    = factor("log2(Lift)", levels=c("NPMI","log2(Lift)")),
    value     = l2l_clip
  )

HH <- bind_rows(D_heat1, D_heat2)

p_heat <- ggplot(HH, aes(x=A, y=C, fill=value)) +
  geom_tile() +
  facet_wrap(~ metric, ncol=1, scales="free_y") +
  scale_fill_gradient2(
    low="#4575b4", mid="#ffffbf", high="#d73027",
    midpoint=0, name="Value"
  ) +
  labs(
    title    = "A–C Coherence Heatmap",
    subtitle = basename(f_npmi),
    x="A term", y="Outcome (C)"
  ) +
  theme_minimal(base_size=12) +
  theme(
    text = element_text(family=jpfont),
    axis.text.x = element_text(angle=60, hjust=1, vjust=1, size=7),
    panel.grid = element_blank()
  )

f_heat <- file.path(DIR_FIG, paste0("ac_npmi_lift_heatmap_",STAMP,".pdf"))
ggsave(f_heat, p_heat, device=cairo_pdf_device, width=10, height=8)
message("Saved heatmap: ", f_heat)

############################################################
# 4) Scatter (NPMI vs log2(Lift)) — Figure 3B
############################################################

th_npmi <- 0.05
th_l2l  <- log2(1.20)

LABEL_PER_C <- 8

lab_df <- D %>%
  group_by(C) %>%
  arrange(desc(npmi + 0.5*log2_lift), .by_group = TRUE) %>%
  slice_head(n = LABEL_PER_C) %>%
  ungroup()

p_sc <- ggplot(D, aes(x=npmi, y=log2_lift)) +
  geom_hline(yintercept=th_l2l, linetype="dashed", size=0.3) +
  geom_vline(xintercept=th_npmi, linetype="dashed", size=0.3) +
  geom_point(aes(size=pAC, color=C), alpha=0.8) +
  geom_text(
    data = lab_df,
    aes(label=A),
    family=jpfont, size=3, nudge_y=0.03, check_overlap=TRUE
  ) +
  facet_wrap(~ C, scales="free") +
  scale_size_continuous(name="pAC (co-occur rate)", range=c(1,5)) +
  scale_color_discrete(name="Outcome (C)") +
  labs(
    title    = "A–C Coherence Scatter (NPMI vs log2(Lift))",
    subtitle = glue("Guides: NPMI ≥ {th_npmi}, Lift ≥ 1.2"),
    x="NPMI", y="log2(Lift)"
  ) +
  theme_minimal(base_size=12) +
  theme(
    text = element_text(family=jpfont),
    panel.grid.minor = element_blank()
  )

f_sc <- file.path(DIR_FIG, paste0("ac_npmi_lift_scatter_",STAMP,".pdf"))
ggsave(f_sc, p_sc, device=cairo_pdf_device, width=12, height=8.5)
message("Saved scatter: ", f_sc)

############################################################
# END
############################################################
