############################################################
# 05) ABC triad score network — ORIGINAL
# ----------------------------------------------------------
# Reproduces Figure 4 of the RA-ILD manuscript.
#
# Inputs:
#   output/abc_edges_top*.csv   (generated by 01 or by your triad extraction)
#
# Outputs:
#   fig_pub/abc_network_top{N}_{STAMP}.pdf
#
# This is the original logic from:
#   - ABC network code (abc_network_top3.txt)
#   - The refined final code inside Figure調整用追加コード.rtf
#
# with:
#   - ROOT generalized
#   - font = "sans"
############################################################

suppressPackageStartupMessages({
  library(dplyr); library(readr); library(stringr)
  library(igraph); library(ggraph); library(ggplot2)
})

ROOT    <- "/path/to/RA-ILD_textanalysis"
DIR_OUT <- file.path(ROOT, "output")
DIR_FIG <- file.path(ROOT, "fig_pub"); dir.create(DIR_FIG, recursive = TRUE)
DIR_DIC <- file.path(ROOT, "dic")

# ---- pick latest edges file ----
pick_latest <- function(pattern, dir=DIR_OUT){
  xs <- Sys.glob(file.path(dir, pattern))
  if (!length(xs)) stop("abc_edges_top*.csv not found in: ", dir)
  xs[which.max(file.info(xs)$mtime)]
}

edges_csv <- pick_latest("abc_edges_top*.csv", DIR_OUT)
edges <- readr::read_csv(edges_csv, show_col_types = FALSE)
bn <- basename(edges_csv)

# infer topN / STAMP
topN  <- suppressWarnings(as.integer(sub("abc_edges_top([0-9]+)_.*","\\1", bn)))
STAMP <- sub(".*_(\\d{8}_\\d{4})\\.csv$","\\1", bn)
if (is.na(topN)){
  topN <- length(unique(paste0(edges$from,"→",edges$to)))
}

############################################################
# Load dictionary for node role mapping
############################################################

dic_path <- if (file.exists(file.path(DIR_DIC,"raalid_pub.csv"))) {
  file.path(DIR_DIC,"raalid_pub.csv")
} else {
  file.path(DIR_DIC,"raalid_v07.csv")
}

dic <- readr::read_csv(dic_path, show_col_types = FALSE)

ROLE_A_CLASSES   <- c("drug","bio","gene","exposure","host","event",
                      "nonpharm","vaccine","population","system","strategy")
ROLE_B_CLASSES   <- c("biomarker","molecular","microbiome","cell",
                      "activity","pft","phenotype","trend","complication")
ROLE_BPR_CLASSES <- c("pattern","radiology","qct","airway")
ROLE_C_CLASSES   <- c("outcome")

role_of <- function(cls){
  dplyr::case_when(
    cls %in% ROLE_C_CLASSES    ~ "C",
    cls %in% ROLE_BPR_CLASSES  ~ "Bprime",
    cls %in% ROLE_B_CLASSES    ~ "B",
    cls %in% ROLE_A_CLASSES    ~ "A",
    TRUE                       ~ "Other"
  )
}

############################################################
# Build graph
############################################################

nodes <- tibble(term = unique(c(edges$from, edges$to))) %>%
  left_join(dic %>% select(term, class), by="term") %>%
  mutate(
    role  = role_of(class),
    label = term
  )

g <- igraph::graph_from_data_frame(edges, directed=TRUE, vertices = nodes)

deg <- igraph::degree(g, mode="all")
V(g)$deg <- deg

# Edge attributes
E(g)$weight <- edges$w
E(g)$kind   <- edges$kind   # "AB"/"BC"

############################################################
# Aesthetic rules (RTF final)
############################################################

jpfont <- "sans"

# colors
col_A      <- "#1b4f72"
col_B      <- "#117a65"
col_Bprime <- "#d35400"
col_C      <- "#b03a2e"
col_Other  <- "#7d7d7d"

col_edge_AB <- "#e74c3c"  # red
col_edge_BC <- "#2471a3"  # blue

############################################################
# Plot
############################################################

set.seed(123)

p <- ggraph::ggraph(g, layout="fr") +
  # edges: AB=red, BC=blue
  ggraph::geom_edge_link(
    aes(edge_colour = kind, edge_width = weight),
    alpha = 0.6
  ) +
  # nodes: shape by role, size by degree
  ggraph::geom_node_point(
    aes(shape = role, size = deg, fill = role),
    colour = "grey20", stroke = 0.7
  ) +
  ggraph::geom_node_text(
    aes(label = label),
    family = jpfont, size = 3, repel = TRUE
  ) +
  # edge scales
  ggraph::scale_edge_colour_manual(
    values = c(AB = col_edge_AB, BC = col_edge_BC),
    labels = c(AB = "AB (A → B)", BC = "BC (B → C)"),
    name   = "Edge type"
  ) +
  ggraph::scale_edge_width_continuous(
    range = c(0.4, 2.5),
    name  = "PMID evidence"
  ) +
  # node colors
  scale_shape_manual(
    values = c(
      A      = 22,
      B      = 21,
      Bprime = 21,
      C      = 23,
      Other  = 24
    )
  ) +
  scale_fill_manual(
    values = c(
      A      = col_A,
      B      = col_B,
      Bprime = col_Bprime,
      C      = col_C,
      Other  = col_Other
    )
  ) +
  scale_size_continuous(range = c(3,9), guide="none") +
  labs(
    title    = sprintf("ABC network (Top %d)", topN),
    subtitle = "AB edges = red; BC edges = blue; edge width ∝ PMID evidence",
    x=NULL, y=NULL
  ) +
  theme_minimal(base_size=11) +
  theme(
    text = element_text(family=jpfont),
    legend.position = "bottom",
    panel.grid = element_blank()
  )

############################################################
# Save
############################################################

out_pdf <- file.path(DIR_FIG, sprintf("abc_network_top%d_%s.pdf", topN, STAMP))
ggsave(out_pdf, plot = p, device = cairo_pdf_device, width = 9, height = 6)
message("Saved: ", out_pdf)

############################################################
# END
############################################################
