############################################################
# 07) White-map refinement + B-breakdown + fallback2 — ORIGINAL
# -------------------------------------------------------------
# Reproduces Figure 5C of the RA-ILD manuscript.
#
# Inputs (generated by 03_whiteMap_preanalysis_core.R):
#   white_map_candidates_*.csv
#   top_white_candidates_*.csv
#
# Additional dependency:
#   hits_matrix_*.csv   (for fallback2 counting)
#
# Outputs:
#   fig_pub/whiteMap_Bbreakdown_{STAMP}.pdf
#
# Adjustments:
#   - ROOT generalized
#   - jpfont = "sans"
#   - A_LIST at top allows specifying which A to plot
#
############################################################

suppressPackageStartupMessages({
  library(dplyr); library(readr); library(stringr)
  library(tidyr); library(ggplot2); library(forcats)
  library(glue)
})

ROOT <- "/path/to/RA-ILD_textanalysis"

DIR_OUT <- file.path(ROOT,"output")
DIR_FIG <- file.path(ROOT,"fig_pub")
DIR_DAT <- file.path(ROOT,"data_proc")
dir.create(DIR_FIG, recursive=TRUE, showWarnings=FALSE)

jpfont <- "sans"
cairo_pdf_device <- grDevices::cairo_pdf

STAMP <- format(Sys.time(), "%Y%m%d_%H%M")

############################################################
# 0) Which A terms to show in the 3-panel? (as in Fig 5C)
############################################################
# You can edit this manually. The following matches the manuscript:
A_LIST <- c("male_sex","MUC5B","smoking")

############################################################
# 1) Load required files
############################################################

# get latest helper
pick_latest <- function(pattern, dirs){
  xs <- unlist(lapply(dirs, function(d) Sys.glob(file.path(d, pattern))))
  if (!length(xs)) return(NA_character_)
  xs[which.max(file.info(xs)$mtime)]
}

f_white <- pick_latest("white_map_candidates_*.csv", DIR_OUT)
f_top10 <- pick_latest("top_white_candidates_*.csv", DIR_OUT)
f_hits  <- pick_latest("hits_matrix_*.csv", DIR_DAT)

stopifnot(!is.na(f_white), !is.na(f_top10), !is.na(f_hits))

white_map <- readr::read_csv(f_white, show_col_types=FALSE)
top10     <- readr::read_csv(f_top10, show_col_types=FALSE)
hits      <- readr::read_csv(f_hits,  show_col_types=FALSE)

############################################################
# 2) Prepare B-breakdown data
# ----------------------------------------------------------
# white_map contains AB/BC evidence summary values:
#   AB_evi_sum, BC_evi_sum, AB_evi_max, BC_evi_max, n_B
#
# fallback2 uses actual co-occurrence:
#   #(A and B) + #(B and AE-ILD)
############################################################

# C-term for AE-ILD must exist in hits:
C_AE <- "AE-ILD"
hitcol_C <- paste0("hit__", C_AE)
stopifnot(hitcol_C %in% names(hits))

binv <- function(v) as.integer(ifelse(is.na(v),0L,v>0L))

get_hit <- function(t){
  col <- paste0("hit__",t)
  if (!(col %in% names(hits))) return(integer(nrow(hits)))
  binv(hits[[col]])
}

# Unique B candidates appearing in white_map
# (from the logic in ABC ranking; B are intermediates)
# In refined RTF code, B is embedded—this reconstructs mapping:
all_B <- unique(white_map$B) %>% sort()

############################################################
# 3) Function to compute breakdown for a given A
############################################################
compute_breakdown <- function(A_term){

  # B candidates linked to A
  sub <- white_map %>% filter(A == A_term)
  if (!nrow(sub)) return(NULL)

  out <- lapply(seq_len(nrow(sub)), function(i){
    B_term <- sub$B[i]

    hitA <- get_hit(A_term)
    hitB <- get_hit(B_term)
    hitC <- get_hit(C_AE)  # AE-ILD only

    # fallback2: AB + BC document counts
    AB_n <- sum(hitA & hitB)
    BC_n <- sum(hitB & hitC)
    fallback2_strength <- AB_n + BC_n

    tibble(
      A = A_term,
      B = B_term,
      AB_n11 = AB_n,
      BC_n11 = BC_n,
      fallback2_strength = fallback2_strength,
      ABBC_strength = sub$ABBC_strength[i]
    )
  }) |>
    bind_rows() |>
    arrange(desc(fallback2_strength))

  out
}

############################################################
# 4) Build the combined table for selected A
############################################################

df_list <- lapply(A_LIST, compute_breakdown)
names(df_list) <- A_LIST

# clean empty
df_list <- df_list[!vapply(df_list, function(x) is.null(x) || !nrow(x), logical(1))]

############################################################
# 5) Plot 3-panel B-breakdown (as in Figure 5C)
############################################################

plot_one <- function(dfA){
  A_term <- unique(dfA$A)

  dfA %>%
    mutate(
      B_f = forcats::fct_reorder(B, fallback2_strength),
      label = B
    ) %>%
    ggplot(aes(x = fallback2_strength, y = B_f)) +
    geom_point(aes(size = fallback2_strength),
               shape=21, fill="steelblue", color="black", alpha=0.8) +
    geom_segment(aes(x=0, xend=fallback2_strength, y=B_f, yend=B_f),
                 linewidth=0.6, alpha=0.6) +
    scale_size_continuous(range=c(2.5,10), guide="none") +
    labs(
      title = glue("B-breakdown for {A_term} → {C_AE}"),
      x = "(A & B) + (B & AE-ILD)",
      y = "Intermediate B"
    ) +
    theme_minimal(base_size=12) +
    theme(text = element_text(family=jpfont))
}

plist <- lapply(df_list, plot_one)

# Combine all panels vertically
p_all <- cowplot::plot_grid(plotlist = plist, ncol=1, align="v")

############################################################
# 6) Save (Figure 5C)
############################################################

outfile <- file.path(DIR_FIG, paste0("whiteMap_Bbreakdown_",STAMP,".pdf"))
ggplot2::ggsave(outfile, p_all, device=cairo_pdf_device, width=10, height=12)
message("Saved: ", outfile)

############################################################
# END
############################################################
